import 'package:flutter/widgets.dart';

/// Explanatory sentences of the Sound tab (en / ru / uz). The head-unit labels themselves
/// (EQ, SUPER BASS, HPF ...) stay in English exactly like on the real Carrozzeria display.
String soundText(BuildContext context, String key) {
  final lang = Localizations.maybeLocaleOf(context)?.languageCode ?? 'en';
  final table = _strings[lang] ?? _strings['en']!;
  return table[key] ?? _strings['en']![key] ?? key;
}

const _strings = <String, Map<String, String>>{
  'en': {
    'dsp_missing_title': 'DSP engine not loaded',
    'dsp_missing_body': 'The native Carrozzeria DSP library could not be loaded on this device. Your settings are still saved and will be applied as soon as the engine is available.',
    'bypass_on': 'Bypass: you are hearing the original signal.',
    'bypass_off': 'DSP active: every sample runs through the Carrozzeria engine.',
    'asr_help': 'Advanced Sound Retriever restores the highs and dynamics lost in compressed audio (streaming, Bluetooth). MODE1 is gentle, MODE2 is stronger and best for low bit-rate sources.',
    'sla_help': 'Source Level Adjuster evens out the volume between sources.',
    'fader_network': 'Fader is not available in Network mode.',
    'auto_headroom_help': 'Lowers the input by half of the largest boost so EQ and bass boost never clip.',
    'crossfeed_help': 'Blends a little of each channel into the other for a natural headphone image.',
    'output_help': 'CAR SPEAKERS keeps the full car processing; HEADPHONES adds crossfeed.',
    'ta_help': 'Enter the distance from the listening position to each speaker. The farthest speaker plays without delay; closer ones are delayed so that all sound arrives at the same time.',
    'ta_off': 'Time alignment is OFF. Choose a listening position or edit a distance.',
    'ta_custom': 'Custom distances are used.',
    'xo_help': 'Tap a channel to edit it. The graph shows the real filter response computed by the engine.',
    'xo_lr_note': 'Linkwitz-Riley is only available with -12, -24 or -36 dB/oct slopes.',
    'sf_off_note': 'Sound Field is OFF. Choose a mode to hear the room.',
    'decay_none': 'No active Sound Field',
    'conv_no_ir':
        'No impulse response is assigned to this mode and size. The algorithmic engine is used until you assign one.',
    'conv_fallback': 'Using the IR assigned to another size of this mode.',
    'sf_tune_help': 'These values define each algorithmic room. Tune by ear against the real head unit, then export the table to share it.',
    'sf_reset_confirm': 'Restore the factory Sound Field table?',
    'sf_import_ok': 'Sound Field table imported.',
    'sf_import_fail': 'This file is not a valid Sound Field table.',
    'profile_saved': 'Profile saved.',
    'profile_loaded': 'Profile loaded.',
    'profile_import_ok': 'Profile imported and applied.',
    'profile_import_fail': 'This file is not a valid CarroTube sound profile.',
    'profile_empty': 'No saved profiles yet. Save the current sound to keep it.',
    'confirm_reset_all': 'Reset every sound setting to factory defaults?',
    'confirm_delete': 'Delete "{name}"?',
    'profile_name': 'Profile name',
    'ir_name': 'IR name',
    'ir_assigned': 'IR assigned to {slot}.',
    'ir_saved': 'IR saved and assigned to {slot}. Convolution engine enabled.',
    'ir_library_empty': 'Your IR library is empty. Capture an IR from your head unit or import a WAV file (for example one exported from REW).',
    'ir_import_help': 'Import a WAV impulse response (mono, stereo or 4-channel true stereo; 16/24/32-bit or float).',
    'ir_assign_slot': 'Assign to Sound Field slot',
    'ir_no_assign': 'Only add to library',
    'error_generic': 'Something went wrong: {error}',
    'wiz_1_title': 'Prepare the head unit',
    'wiz_1_body': 'On the real head unit set EQ to FLAT and switch off every effect: LOUDNESS, BASS BOOST, ASR, SLA 0, TIME ALIGNMENT OFF, crossover filters OFF, FADER/BALANCE centred. Then select only the Sound Field mode and size you want to capture. The captured IR will be stored in that slot here.',
    'wiz_1_level': 'Set the head unit volume to about 2/3. You will fine-tune it during the level check.',
    'wiz_2_title': 'Connections',
    'wiz_2_usb': 'Recommended: a USB audio interface connected to this phone. Interface OUTPUT L/R -> head unit AUX IN. Head unit RCA pre-out (front L/R) -> interface INPUT L/R. This captures the pure electrical response of the Sound Field.',
    'wiz_2_bt': 'Alternative: play the sweep into the head unit over Bluetooth or USB and record the RCA pre-out with the interface input.',
    'wiz_2_mic': 'Fallback: no interface. Play the sweep into the head unit and use the phone microphone placed at the driver\'s head position, pointing up. Keep the car quiet and closed; the IR will also contain the car acoustics.',
    'wiz_3_title': 'Audio route and microphone',
    'wiz_3_body': 'Check that the input and output below are the devices you connected, then allow microphone access.',
    'wiz_3_granted': 'Microphone access granted.',
    'wiz_3_denied': 'Microphone access denied. Allow it in system settings to capture.',
    'wiz_4_title': 'Level check and capture',
    'wiz_4_body': 'Each capture plays a 10 s sine sweep and records 4 s more for the reverb tail. Capture the LEFT channel first, then the RIGHT channel (true-stereo IR). Stay quiet during the recording.',
    'wiz_4_level_low': 'Level is very low. Raise the head unit volume or the interface input gain and capture again.',
    'wiz_4_level_clip': 'The recording is clipping. Lower the volume or the input gain and capture again.',
    'wiz_4_level_ok': 'Level looks good.',
    'wiz_5_title': 'Processing',
    'wiz_5_body': 'The sweeps are deconvolved into an impulse response (maximum 6 s).',
    'wiz_5_done': 'Impulse response ready.',
    'wiz_6_title': 'Name and save',
    'wiz_6_body': 'The IR is added to your library, assigned to the chosen slot and the Sound Field switches to the convolution engine.',
    'wiz_capture_failed': 'Capture failed: {error}',
    'wiz_need_both': 'Capture both LEFT and RIGHT to continue.',
  },
  'ru': {
    'dsp_missing_title': 'DSP-движок не загружен',
    'dsp_missing_body': 'Нативная библиотека Carrozzeria DSP не загрузилась на этом устройстве. Настройки сохраняются и будут применены, как только движок станет доступен.',
    'bypass_on': 'Обход: вы слышите исходный сигнал.',
    'bypass_off': 'DSP включён: каждый сэмпл проходит через движок Carrozzeria.',
    'asr_help': 'Advanced Sound Retriever восстанавливает верхние частоты и динамику, потерянные при сжатии (стриминг, Bluetooth). MODE1 — мягкий, MODE2 — сильнее, лучше для источников с низким битрейтом.',
    'sla_help': 'Source Level Adjuster выравнивает громкость между источниками.',
    'fader_network': 'Фейдер недоступен в режиме Network.',
    'auto_headroom_help': 'Снижает вход на половину наибольшего подъёма, чтобы EQ и bass boost не вызывали клиппинг.',
    'crossfeed_help': 'Подмешивает немного каждого канала в другой для естественной картины в наушниках.',
    'output_help': 'CAR SPEAKERS — полная обработка для машины; HEADPHONES добавляет crossfeed.',
    'ta_help': 'Укажите расстояние от точки прослушивания до каждого динамика. Самый дальний играет без задержки, ближние задерживаются, чтобы звук приходил одновременно.',
    'ta_off': 'Временная задержка выключена. Выберите позицию прослушивания или измените расстояние.',
    'ta_custom': 'Используются собственные расстояния.',
    'xo_help': 'Нажмите на канал, чтобы изменить его. График показывает реальную АЧХ фильтров, рассчитанную движком.',
    'xo_lr_note': 'Linkwitz-Riley доступен только с крутизной -12, -24 или -36 дБ/окт.',
    'sf_off_note': 'Sound Field выключен. Выберите режим, чтобы услышать зал.',
    'decay_none': 'Sound Field не активен',
    'conv_no_ir': 'Для этого режима и размера не назначен импульсный отклик. Пока используется алгоритмический движок.',
    'conv_fallback': 'Используется IR, назначенный другому размеру этого режима.',
    'sf_tune_help': 'Эти значения задают каждый алгоритмический зал. Настройте на слух по реальной магнитоле и экспортируйте таблицу.',
    'sf_reset_confirm': 'Восстановить заводскую таблицу Sound Field?',
    'sf_import_ok': 'Таблица Sound Field импортирована.',
    'sf_import_fail': 'Файл не является таблицей Sound Field.',
    'profile_saved': 'Профиль сохранён.',
    'profile_loaded': 'Профиль загружен.',
    'profile_import_ok': 'Профиль импортирован и применён.',
    'profile_import_fail': 'Файл не является звуковым профилем CarroTube.',
    'profile_empty': 'Сохранённых профилей пока нет. Сохраните текущий звук.',
    'confirm_reset_all': 'Сбросить все настройки звука к заводским?',
    'confirm_delete': 'Удалить «{name}»?',
    'profile_name': 'Название профиля',
    'ir_name': 'Название IR',
    'ir_assigned': 'IR назначен в {slot}.',
    'ir_saved': 'IR сохранён и назначен в {slot}. Включён движок свёртки.',
    'ir_library_empty': 'Библиотека IR пуста. Снимите IR с магнитолы или импортируйте WAV (например, из REW).',
    'ir_import_help':
        'Импорт WAV импульсного отклика (моно, стерео или 4-канальный true stereo; 16/24/32 бит или float).',
    'ir_assign_slot': 'Назначить в слот Sound Field',
    'ir_no_assign': 'Только добавить в библиотеку',
    'error_generic': 'Ошибка: {error}',
    'wiz_1_title': 'Подготовка магнитолы',
    'wiz_1_body': 'На магнитоле установите EQ в FLAT и выключите все эффекты: LOUDNESS, BASS BOOST, ASR, SLA 0, TIME ALIGNMENT OFF, фильтры кроссовера OFF, FADER/BALANCE по центру. Затем включите только нужный режим и размер Sound Field. Снятый IR будет сохранён в этот слот.',
    'wiz_1_level': 'Громкость магнитолы — примерно 2/3. Точнее настроите при проверке уровня.',
    'wiz_2_title': 'Подключение',
    'wiz_2_usb': 'Рекомендуется: USB аудиоинтерфейс, подключённый к телефону. Выход интерфейса L/R -> AUX IN магнитолы. RCA предвыход магнитолы (front L/R) -> вход интерфейса L/R. Так снимается чистый электрический отклик Sound Field.',
    'wiz_2_bt': 'Альтернатива: воспроизводите свип в магнитолу по Bluetooth или USB и записывайте RCA предвыход входом интерфейса.',
    'wiz_2_mic': 'Запасной вариант: без интерфейса. Воспроизводите свип в магнитолу и используйте микрофон телефона у головы водителя, направленный вверх. В машине должно быть тихо и закрыто; IR будет содержать и акустику салона.',
    'wiz_3_title': 'Аудиомаршрут и микрофон',
    'wiz_3_body': 'Проверьте, что вход и выход ниже — это подключённые устройства, затем разрешите доступ к микрофону.',
    'wiz_3_granted': 'Доступ к микрофону разрешён.',
    'wiz_3_denied': 'Доступ к микрофону запрещён. Разрешите его в настройках системы.',
    'wiz_4_title': 'Проверка уровня и запись',
    'wiz_4_body': 'Каждая запись воспроизводит свип 10 с и записывает ещё 4 с хвоста реверберации. Сначала снимите ЛЕВЫЙ канал, затем ПРАВЫЙ (true-stereo IR). Во время записи соблюдайте тишину.',
    'wiz_4_level_low': 'Уровень очень низкий. Увеличьте громкость магнитолы или усиление входа и повторите.',
    'wiz_4_level_clip': 'Запись перегружена. Уменьшите громкость или усиление входа и повторите.',
    'wiz_4_level_ok': 'Уровень в норме.',
    'wiz_5_title': 'Обработка',
    'wiz_5_body': 'Свипы деконволюируются в импульсный отклик (максимум 6 с).',
    'wiz_5_done': 'Импульсный отклик готов.',
    'wiz_6_title': 'Название и сохранение',
    'wiz_6_body':
        'IR добавляется в библиотеку, назначается в выбранный слот, и Sound Field переключается на движок свёртки.',
    'wiz_capture_failed': 'Запись не удалась: {error}',
    'wiz_need_both': 'Снимите LEFT и RIGHT, чтобы продолжить.',
  },
  'uz': {
    'dsp_missing_title': 'DSP dvigateli yuklanmadi',
    'dsp_missing_body': 'Carrozzeria DSP native kutubxonasi bu qurilmada yuklanmadi. Sozlamalar saqlanadi va dvigatel ishga tushishi bilan qo\'llaniladi.',
    'bypass_on': 'Bypass: siz asl signalni eshityapsiz.',
    'bypass_off': 'DSP yoqilgan: har bir sempl Carrozzeria dvigatelidan o\'tadi.',
    'asr_help': 'Advanced Sound Retriever siqilgan audioda (striming, Bluetooth) yo\'qolgan yuqori chastotalar va dinamikani tiklaydi. MODE1 yumshoq, MODE2 kuchliroq — past bitreytli manbalar uchun.',
    'sla_help': 'Source Level Adjuster manbalar orasidagi ovoz balandligini tenglashtiradi.',
    'fader_network': 'Network rejimida fader ishlamaydi.',
    'auto_headroom_help':
        'EQ va bass boost klipping bermasligi uchun kirishni eng katta ko\'tarilishning yarmiga pasaytiradi.',
    'crossfeed_help': 'Quloqchinda tabiiy tovush uchun har bir kanaldan ozgina boshqasiga qo\'shadi.',
    'output_help': 'CAR SPEAKERS — mashina uchun to\'liq ishlov; HEADPHONES crossfeed qo\'shadi.',
    'ta_help': 'Tinglash nuqtasidan har bir karnaygacha bo\'lgan masofani kiriting. Eng uzoq karnay kechikishsiz chaladi, yaqinlari esa tovush bir vaqtda yetib kelishi uchun kechiktiriladi.',
    'ta_off': 'Time alignment o\'chirilgan. Tinglash joyini tanlang yoki masofani o\'zgartiring.',
    'ta_custom': 'Shaxsiy masofalar ishlatilmoqda.',
    'xo_help': 'Tahrirlash uchun kanalni tanlang. Grafik dvigatel hisoblagan haqiqiy filtr javobini ko\'rsatadi.',
    'xo_lr_note': 'Linkwitz-Riley faqat -12, -24 yoki -36 dB/okt qiyalikda mavjud.',
    'sf_off_note': 'Sound Field o\'chiq. Zalni eshitish uchun rejim tanlang.',
    'decay_none': 'Faol Sound Field yo\'q',
    'conv_no_ir': 'Bu rejim va o\'lcham uchun impuls javob biriktirilmagan. Hozircha algoritmik dvigatel ishlaydi.',
    'conv_fallback': 'Shu rejimning boshqa o\'lchamiga biriktirilgan IR ishlatilmoqda.',
    'sf_tune_help': 'Bu qiymatlar har bir algoritmik zalni belgilaydi. Haqiqiy magnitolaga quloq solib sozlang va jadvalni eksport qiling.',
    'sf_reset_confirm': 'Zavod Sound Field jadvalini tiklaysizmi?',
    'sf_import_ok': 'Sound Field jadvali import qilindi.',
    'sf_import_fail': 'Bu fayl Sound Field jadvali emas.',
    'profile_saved': 'Profil saqlandi.',
    'profile_loaded': 'Profil yuklandi.',
    'profile_import_ok': 'Profil import qilindi va qo\'llanildi.',
    'profile_import_fail': 'Bu fayl CarroTube ovoz profili emas.',
    'profile_empty': 'Saqlangan profillar yo\'q. Joriy ovozni saqlang.',
    'confirm_reset_all': 'Barcha ovoz sozlamalarini zavod holatiga qaytarasizmi?',
    'confirm_delete': '"{name}" o\'chirilsinmi?',
    'profile_name': 'Profil nomi',
    'ir_name': 'IR nomi',
    'ir_assigned': 'IR {slot} ga biriktirildi.',
    'ir_saved': 'IR saqlandi va {slot} ga biriktirildi. Konvolyutsiya dvigateli yoqildi.',
    'ir_library_empty':
        'IR kutubxonasi bo\'sh. Magnitoladan IR yozib oling yoki WAV faylni (masalan REW dan) import qiling.',
    'ir_import_help':
        'WAV impuls javobini import qilish (mono, stereo yoki 4 kanalli true stereo; 16/24/32 bit yoki float).',
    'ir_assign_slot': 'Sound Field slotiga biriktirish',
    'ir_no_assign': 'Faqat kutubxonaga qo\'shish',
    'error_generic': 'Xatolik: {error}',
    'wiz_1_title': 'Magnitolani tayyorlash',
    'wiz_1_body': 'Magnitolada EQ ni FLAT qiling va barcha effektlarni o\'chiring: LOUDNESS, BASS BOOST, ASR, SLA 0, TIME ALIGNMENT OFF, krossover filtrlari OFF, FADER/BALANCE markazda. So\'ng faqat kerakli Sound Field rejimi va o\'lchamini yoqing. Yozilgan IR shu slotga saqlanadi.',
    'wiz_1_level': 'Magnitola ovozini taxminan 2/3 ga qo\'ying. Aniq sozlashni daraja tekshiruvida qilasiz.',
    'wiz_2_title': 'Ulanishlar',
    'wiz_2_usb': 'Tavsiya: telefonga ulangan USB audio interfeys. Interfeys chiqishi L/R -> magnitola AUX IN. Magnitola RCA pre-out (front L/R) -> interfeys kirishi L/R. Bu Sound Field ning sof elektr javobini yozib oladi.',
    'wiz_2_bt': 'Muqobil: sweep ni magnitolaga Bluetooth yoki USB orqali bering va RCA pre-out ni interfeys kirishi bilan yozing.',
    'wiz_2_mic': 'Zaxira variant: interfeyssiz. Sweep ni magnitolaga bering va telefon mikrofonini haydovchi boshi joyiga, tepaga qaratib qo\'ying. Mashina yopiq va jim bo\'lsin; IR salon akustikasini ham o\'z ichiga oladi.',
    'wiz_3_title': 'Audio yo\'nalish va mikrofon',
    'wiz_3_body':
        'Quyidagi kirish va chiqish siz ulagan qurilmalar ekanini tekshiring, so\'ng mikrofonga ruxsat bering.',
    'wiz_3_granted': 'Mikrofonga ruxsat berildi.',
    'wiz_3_denied': 'Mikrofonga ruxsat berilmadi. Tizim sozlamalarida ruxsat bering.',
    'wiz_4_title': 'Darajani tekshirish va yozish',
    'wiz_4_body': 'Har bir yozuv 10 s sweep chaladi va reverb dumi uchun yana 4 s yozadi. Avval CHAP kanalni, keyin O\'NG kanalni yozing (true-stereo IR). Yozuv vaqtida jim turing.',
    'wiz_4_level_low':
        'Daraja juda past. Magnitola ovozini yoki interfeys kirish kuchaytirishini oshirib qayta yozing.',
    'wiz_4_level_clip': 'Yozuv klipping bermoqda. Ovozni yoki kirish kuchaytirishini pasaytirib qayta yozing.',
    'wiz_4_level_ok': 'Daraja yaxshi.',
    'wiz_5_title': 'Ishlov berish',
    'wiz_5_body': 'Sweep lar impuls javobga dekonvolyutsiya qilinadi (maksimal 6 s).',
    'wiz_5_done': 'Impuls javob tayyor.',
    'wiz_6_title': 'Nomlash va saqlash',
    'wiz_6_body':
        'IR kutubxonaga qo\'shiladi, tanlangan slotga biriktiriladi va Sound Field konvolyutsiya dvigateliga o\'tadi.',
    'wiz_capture_failed': 'Yozib bo\'lmadi: {error}',
    'wiz_need_both': 'Davom etish uchun LEFT va RIGHT ni yozing.',
  },
};
