import AVFoundation
import Flutter

#if canImport(CarroDSP)
  import CarroDSP
#endif

/// Recording side of the impulse-response capture wizard.
///
/// Plays an exponential sine sweep (generated by the C++ core so the deconvolution uses
/// exactly the same signal) on the left, right or both output channels and records the
/// current input (USB audio interface connected to the head unit's RCA outputs, or the
/// phone microphone) for the sweep plus a tail. The recording is written as a 32-bit float
/// WAV; Dart then calls carro_ir_build_from_captures() to deconvolve it.
final class CarroIRCapture {
  private var engine: AVAudioEngine?
  private var node: AVAudioPlayerNode?
  private var recordedL: [Float] = []
  private var recordedR: [Float] = []
  private var inputChannels = 1
  private let queue = DispatchQueue(label: "uz.carrotube.ircapture")
  private var pending: FlutterResult?
  private var finishWork: DispatchWorkItem?
  private weak var player: CarroPlayer?

  func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult, player: CarroPlayer) {
    self.player = player
    let args = call.arguments as? [String: Any] ?? [:]
    switch call.method {
    case "requestMicrophone":
      requestMicrophone { granted in result(granted) }
    case "route":
      result(routeInfo())
    case "capture":
      requestMicrophone { [weak self] granted in
        guard let self else { return }
        guard granted else {
          result(FlutterError(code: "permission", message: "Microphone / audio input permission denied", details: nil))
          return
        }
        self.capture(args, result: result)
      }
    case "cancel":
      cancel()
      result(nil)
    default:
      result(FlutterMethodNotImplemented)
    }
  }

  private func requestMicrophone(_ done: @escaping (Bool) -> Void) {
    if #available(iOS 17.0, *) {
      AVAudioApplication.requestRecordPermission { granted in
        DispatchQueue.main.async { done(granted) }
      }
    } else {
      AVAudioSession.sharedInstance().requestRecordPermission { granted in
        DispatchQueue.main.async { done(granted) }
      }
    }
  }

  private func routeInfo() -> [String: Any] {
    let session = AVAudioSession.sharedInstance()
    let route = session.currentRoute
    let input = route.inputs.first ?? session.preferredInput ?? session.availableInputs?.first
    return [
      "input": input?.portName ?? "none",
      "inputType": input?.portType.rawValue ?? "none",
      "inputChannels": input?.channels?.count ?? 0,
      "output": route.outputs.first?.portName ?? "none",
      "outputType": route.outputs.first?.portType.rawValue ?? "none",
      "sampleRate": session.sampleRate,
      "availableInputs": (session.availableInputs ?? []).map { $0.portName },
    ]
  }

  private func capture(_ args: [String: Any], result: @escaping FlutterResult) {
    guard pending == nil else {
      result(FlutterError(code: "busy", message: "A capture is already running", details: nil))
      return
    }
    let channel = (args["channel"] as? NSNumber)?.intValue ?? 2
    let sweepSeconds = (args["sweepSeconds"] as? NSNumber)?.doubleValue ?? 10
    let f1 = (args["f1"] as? NSNumber)?.doubleValue ?? 20
    let f2 = (args["f2"] as? NSNumber)?.doubleValue ?? 20000
    let amplitudeDb = (args["amplitudeDb"] as? NSNumber)?.doubleValue ?? -6
    let tailSeconds = (args["tailSeconds"] as? NSNumber)?.doubleValue ?? 4

    player?.pauseForCapture()
    let session = AVAudioSession.sharedInstance()
    do {
      try session.setCategory(
        .playAndRecord, mode: .measurement, options: [.allowBluetoothA2DP, .defaultToSpeaker])
      try session.setPreferredSampleRate(48000)
      try session.setActive(true)
    } catch {
      restoreSession()
      result(FlutterError(code: "session", message: error.localizedDescription, details: nil))
      return
    }

    let engine = AVAudioEngine()
    let input = engine.inputNode
    let inFormat = input.inputFormat(forBus: 0)
    guard inFormat.channelCount > 0, inFormat.sampleRate > 0 else {
      restoreSession()
      result(FlutterError(code: "no_input", message: "No audio input available", details: nil))
      return
    }
    let outRate = engine.outputNode.outputFormat(forBus: 0).sampleRate > 0
      ? engine.outputNode.outputFormat(forBus: 0).sampleRate : 48000
    guard let format = AVAudioFormat(standardFormatWithSampleRate: outRate, channels: 2) else {
      restoreSession()
      result(FlutterError(code: "format", message: "Unsupported output format", details: nil))
      return
    }

    // Stimulus: 0.5 s silence, sweep, tail silence.
    let lead = Int(0.5 * outRate)
    let sweepFrames = Int(sweepSeconds * outRate)
    let total = lead + sweepFrames + Int(tailSeconds * outRate)
    guard let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: AVAudioFrameCount(total)),
      let channels = buffer.floatChannelData
    else {
      restoreSession()
      result(FlutterError(code: "memory", message: "Cannot allocate the sweep buffer", details: nil))
      return
    }
    buffer.frameLength = AVAudioFrameCount(total)
    for ch in 0..<2 {
      channels[ch].update(repeating: 0, count: total)
    }
    let amplitude = Float(pow(10.0, amplitudeDb / 20.0))
    let sweep = CarroAudioBridge.sweep(
      withFrames: Int32(sweepFrames), sampleRate: outRate, f1: f1, f2: f2, amplitude: amplitude)
    sweep.withUnsafeBytes { raw in
      let src = raw.bindMemory(to: Float.self)
      for ch in 0..<2 where channel == 2 || channel == ch {
        let dst = channels[ch]
        for i in 0..<min(sweepFrames, src.count) {
          dst[lead + i] = src[i]
        }
      }
    }

    let playerNode = AVAudioPlayerNode()
    engine.attach(playerNode)
    engine.connect(playerNode, to: engine.mainMixerNode, format: format)
    engine.mainMixerNode.outputVolume = 1

    inputChannels = min(Int(inFormat.channelCount), 2)
    queue.sync {
      recordedL = []
      recordedR = []
      recordedL.reserveCapacity(Int(Double(total) * inFormat.sampleRate / outRate) + 48000)
      if inputChannels > 1 { recordedR.reserveCapacity(recordedL.capacity) }
    }
    let chCount = inputChannels
    input.installTap(onBus: 0, bufferSize: 4096, format: inFormat) { [weak self] buf, _ in
      guard let self, let data = buf.floatChannelData else { return }
      let n = Int(buf.frameLength)
      let left = Array(UnsafeBufferPointer(start: data[0], count: n))
      let right = chCount > 1 ? Array(UnsafeBufferPointer(start: data[1], count: n)) : []
      self.queue.async {
        self.recordedL.append(contentsOf: left)
        if !right.isEmpty { self.recordedR.append(contentsOf: right) }
      }
    }

    do {
      engine.prepare()
      try engine.start()
    } catch {
      input.removeTap(onBus: 0)
      restoreSession()
      result(FlutterError(code: "engine", message: error.localizedDescription, details: nil))
      return
    }
    playerNode.scheduleBuffer(buffer, at: nil, options: [], completionHandler: nil)
    playerNode.play()

    self.engine = engine
    self.node = playerNode
    self.pending = result
    let duration = Double(total) / outRate + 0.4
    let inRate = inFormat.sampleRate
    let work = DispatchWorkItem { [weak self] in
      self?.finish(outRate: outRate, inRate: inRate)
    }
    finishWork = work
    DispatchQueue.main.asyncAfter(deadline: .now() + duration, execute: work)
  }

  private func stopEngine() {
    engine?.inputNode.removeTap(onBus: 0)
    node?.stop()
    engine?.stop()
    engine = nil
    node = nil
  }

  private func finish(outRate: Double, inRate: Double) {
    stopEngine()
    var interleaved = [Float]()
    var peak: Float = 0
    let channels = inputChannels
    queue.sync {
      let n = channels > 1 ? min(recordedL.count, recordedR.count) : recordedL.count
      interleaved = [Float](repeating: 0, count: n * channels)
      for i in 0..<n {
        let l = recordedL[i]
        interleaved[i * channels] = l
        peak = max(peak, abs(l))
        if channels > 1 {
          let r = recordedR[i]
          interleaved[i * channels + 1] = r
          peak = max(peak, abs(r))
        }
      }
      recordedL = []
      recordedR = []
    }
    let path = (NSTemporaryDirectory() as NSString)
      .appendingPathComponent("carro_capture_\(Int(Date().timeIntervalSince1970 * 1000)).wav")
    let data = interleaved.withUnsafeBufferPointer { Data(buffer: $0) }
    let ok = CarroAudioBridge.writeWav(
      atPath: path, samples: data, channels: Int32(channels), sampleRate: Int32(inRate.rounded()))
    restoreSession()
    let result = pending
    pending = nil
    finishWork = nil
    if ok {
      result?([
        "path": path,
        "sampleRate": outRate,
        "inputSampleRate": inRate,
        "channels": channels,
        "peakDb": peak > 0 ? 20 * log10(Double(peak)) : -120.0,
      ])
    } else {
      result?(FlutterError(code: "io", message: "Could not write the recording", details: nil))
    }
  }

  private func cancel() {
    finishWork?.cancel()
    finishWork = nil
    stopEngine()
    queue.sync {
      recordedL = []
      recordedR = []
    }
    restoreSession()
    pending?(FlutterError(code: "canceled", message: "Capture canceled", details: nil))
    pending = nil
  }

  private func restoreSession() {
    let session = AVAudioSession.sharedInstance()
    try? session.setCategory(.playback, mode: .default, options: [])
    try? session.setActive(true)
    player?.restoreSessionAfterCapture()
  }
}
